version: 3
automerge: true
delete_source_branch_on_merge: true
abort_on_execution_order_fail: true

projects:
- name: luminor-eks-atlantis-dev
  dir: .
  workspace: default
  autoplan:
    enabled: true
    when_modified: ["*.tf", "environments/dev.tfvars", "**/*.tf"]
  apply_requirements: [approved, undiverged]
